name: Final Project
on: push
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: website scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com'