name: Final Project
on: push
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: website scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx
      - name: ZAP Scan
        uses: ./
        id: action-baseline
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          allow_issue_writing: false